### ISSUE TITLE
How to use if already subclassing admin.ModelAdmin

### ISSUE THREAD

**Issue by hakim89** [summernote/django-summernote#263]
I'm using django import_export package and i'm already using the `ImportExportModelAdmin` instead of `admin.ModelAdmin`. Any idea how to use django-summernote with this setup?

**Comment by pincoin** [comment]
Hello,

I am not sure if my idea will work fine because I haven't done it yet.

https://github.com/summernote/django-summernote/blob/master/django_summernote/admin.py

As you can see, we have overridden `formfield_for_dbfield()` method.

If your inherited ModelAdmin class already has this method, you will have to add the following lines in the middle of the method:

https://github.com/summernote/django-summernote/blob/4bfaccda82f8f8f1305fa1922b4cefcb63cf6e51/django_summernote/admin.py#L27-L33

Otherwise, you may just this method `formfield_for_dbfield()` into your custom ModelAdmin class.

If you encounter any problem, feel free to let us know.

Thank you.

**Comment by pincoin** [comment]
I read a document for django-import-export, and it says that it supports mixin

class import_export.admin.ImportExportMixin

http://django-import-export.readthedocs.io/en/latest/api_admin.html#import_export.admin.ImportExportMixin

```
class PostAdmin(ImportExportMixin, SummernoteModelAdmin):
```

I believe that you may try this code, too.

Thank you.

**Comment by hakim89** [comment]
Thank you for your response. It turned out I need the editor in my inline models and I wasn't able to achieve that (looked at the other open issue).
