### ISSUE TITLE
It is not working on server

### ISSUE THREAD

**Issue by harrimkim** [summernote/django-summernote#296]
After reading the README and changing the admin textarea to summernote, it works very well when uploading image in local environment.

I tried applying the exact same code to the aws instance, but I get a 'Failed to save attachment' error in summernote's "SummernoteUploadAttachment".

I'm getting an error in the "#callback save method with attachment parameters as kwargs" section, but I'm not sure what the problem is.

The current server is in user - nginx - uwsgi - django format.

**Comment by lqez** [comment]
Did you run `python manage.py migrate` in production before uploading image files?

**Comment by patabongo** [comment]
I just upgraded to 0.8.10.0 and I'm having the same problem as @harrimkim, uploads are not working and I'm getting an error in production.

My production setup is user - nginx -gunicorn -django. BUT if I try using the built-in Django web server instead of gunicorn on the production server uploads work again and I don't get the error. Any ideas?

**Comment by lqez** [comment]
@harrimkim Please reopen this again with more information and envs.

**Comment by harrimkim** [comment]
im not familar with github. how to reopen this issue?.
and @patabongo i dont think my problem is similar with you because i already check it before.

**Comment by lqez** [comment]
@harrimkim Could you share your AWS information? And if you're using <https://sentry.io/>, this would be the best option to catch error on production.
