### ISSUE TITLE
Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is prohibited

### ISSUE THREAD

**Issue by fbengo** [summernote/django-summernote#346]
```
class FormFromSomeModel(forms.ModelForm):
    class Meta:
        model = SomeModel
        widgets = {
            'foo': SummernoteWidget(),
            'bar': SummernoteInplaceWidget(),
        }
```

**results into:**
`django.core.exceptions.ImproperlyConfigured: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is prohibited`

**Comment by cybaj** [comment]
This error occurs not because of 'widgets'.
It still occurs the error without 'widgets'.

`class FormFromSomeModel(forms.ModelForm):
     class Meta:
         model = SomeModel
        # widgets = {
        #     'foo': SummernoteWidget(),
        #     'bar': SummernoteInplaceWidget(),
        # }
`
results : 
`
django.core.exceptions.ImproperlyConfigured: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is prohibited;`

This error occurs because of not proper usage of ModelForm.
You needs to define fields attributes.

https://docs.djangoproject.com/en/2.1/topics/forms/modelforms/

**Comment by lqez** [comment]
@cybaj Thanks for pointing out.
